
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]

map_type: voxel

obstacle_layer:
  enabled:              true
  obstacle_range:       2.0
  raytrace_range:       2.0
  min_obstacle_height:  0.0
  max_obstacle_height:  0.5
  inflation_radius:     0.2
  origin_z:             0.0
  z_resolution:         0.05
  z_voxels:             20
  unknown_threshold:    5
  mark_threshold:       5
  combination_method:   1
  map_topic:            map
  subscribe_to_updates: false
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  publish_voxel_map:    true
  observation_sources:  pointCloud
  
  pointCloud:
    sensor_frame:       camera_rgb_frame
    data_type:          PointCloud2
    topic:              camera/depth/points
    marking:            true
    clearing:           true
    max_obstacle_height: 0.5
    min_obstacle_height: 0.0

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.25  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  track_unknown_space:  true