global_costmap:
   global_frame:            map
   robot_base_frame:        base_link
   update_frequency:        0.5
   publish_frequency:       2.0
   static_map:              true
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}