local_costmap:
   global_frame:              map
   robot_base_frame:          base_link
   update_frequency:          2.5
   publish_frequency:         2.5
   rolling_window:            true
   width:                     3.0
   height:                    3.0
   resolution:                0.05
   transform_tolerance:       1.0
   always_send_full_costmap:  true

   plugins:
     - {name: obstacle_layer,  type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}