shutdown_costmaps:          false

controller_frequency:       0.5
controller_patience:        15.0

planner_frequency:          0.0
planner_patience:           5.0

oscillation_timeout:        5.0
oscillation_distance:       0.2

base_local_planner:         "teb_local_planner/TebLocalPlannerROS"

base_global_planner:        "global_planner/GlobalPlanner"

clearing_rotation_allowed:  true
max_planning_retries:       5